# before main container starts, it should get the secret from the location init container created
#export it and remove it

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mysql
  # Pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mysql
    spec:
      serviceAccountName: roboshop-mysql
      initContainers:
      - name: secret-reader
        image: amazon/aws-cli
        command:  # storing '.MYSQL_ROOT_PASSWORD' in secrets/mysql-secret.txt
        - sh
        - -c
        - |
            aws secretsmanager get-secret-value --secret-id \
            roboshop/dev/mysql_root_password --query SecretString \
            --output text | jq -r '.MYSQL_ROOT_PASSWORD' > /secrets/mysql-secret.txt 
            echo "Secret fetched successfully"
            cat /secrets/mysql-secret.txt # just for testing, we should not do this
        volumeMounts:
        - name: mysql-secret  # volume is shared between secret-reader init containers and mysql containers
          mountPath: /secrets  
      containers:
      - name: mysql
        image: venkey57/mysql:5.0.0
        args: ["--mysql-native-password=ON"]
        #
        volumeMounts:         # volume is shared between secret-reader init containers and mysql containers
        - name: mysql-secret
          mountPath: /secrets
      volumes:               # disk is added and we give disk access to secret-reader init containers and mysql containers
      - name: mysql-secret
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: mysql
spec:
  selector:
    project: roboshop
    tier: db
    component: mysql
  ports:
    - protocol: TCP
      port: 3306 # service port
      targetPort: 3306 # container port